[features]
seeds = false
[programs.localnet]
anchor_escrow = "82dasQ1WQ1hTqbdpE8aoke5nMrYFLNH8CnuoPSifKqSS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/althea/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
